################### Arabic navigation ####################

# main menu
[[main]]
name = "عن المدرسة"
url = "about/"
weight = 1

[[main]]
name = "الدروس"
url = "course/"
weight = 2

[[main]]
weight = 3
name = "الصفحات"
hasChildren = true

[[main]]
parent = "الصفحات"
name = "ملاحظة"
url = "notice/"

[[main]]
weight = 4
name = "المدرسين"
hasChildren = true

[[main]]
parent = "المدرسين"
name = "Aishatu Abdul-Aziz"
url = "teacher/aishatu-abdul-aziz/"

[[main]]
parent = "المدرسين"
name = "Attik Uthman"
url = "teacher/attik-uthman/"

[[main]]
parent = "المدرسين"
name = "Uthman, Ibrahim Danwa "
url = "teacher/uthman-ibrahim-danwa/"

[[main]]
parent = "المدرسين"
name = "Firdaws Abbas"
url = "teacher/firdaws-abbas/"

[[main]]
parent = "المدرسين"
name = "Sumaiyatu Ibrahim"
url = "teacher/sumaiyatu-ibrahim/"

[[main]]
parent = "المدرسين"
name = "Mardiya yussif"
url = "teacher/yussif-mardiya/"

[[main]]
parent = "المدرسين"
name = " Issahak Suleman "
url = "teacher/issahak-suleman/"

[[main]]
name = "اتصل بنا"
url = "contact/"
weight = 5

[[main]]
name = "Admission"
url = "admission/"
weight = 6



# footer menu

[[footer]]
name = "ملاحظة"
url = "notice/"

[[footer]]
name = "Admission"
url = "admission/"
weight = 6



